//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public ActionInfo()
        {
            this.RoleInfo = new HashSet<RoleInfo>();
        }
    
        public int ActionId { get; set; }
        public string ActionName { get; set; }
        public string ActionUrl { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
    }
}
