//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailActive
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool ActiveState { get; set; }
        public string ActiveToken { get; set; }
        public System.DateTime ActiveTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
