//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayInfo_del
    {
        public string Guid { get; set; }
        public int UserId { get; set; }
        public decimal Money { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int State { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
